### ISSUE TITLE
Don't prompt people to install Advanced Page Cache in Live

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/WordPress#114]
This confuses some customers (per Mason in the Power Users channel). Makes sense. We should have a different message if the env is test or live.

**Comment by jhabdas** [comment]
Why?

**Comment by ataylorme** [comment]
> Why?
The test and live environments are not writeable, therefore the plugin cannot be installed there. It should be installed in the dev or a multidev environment first, then deployed to test and live.

**Comment by jhabdas** [comment]
Oh I see. What would you propose as a change in wording to help make that more clear?

**Comment by nullvariable** [comment]
This looks to be the line in question
https://github.com/pantheon-systems/WordPress/blob/default/wp-content/mu-plugins/pantheon/pantheon-page-cache.php#L212

:ghost: 

I would suggest that instead of linking to the WordPress plugin search (which requires both dev environment and sftp mode) that we instead link to our docs site which explains how to install and configure our caching solutions for WordPress.

This docs page https://pantheon.io/docs/wordpress-cache-plugin looks like it would be the best link to use.
