### ISSUE TITLE
Disable WordPress Update Nag

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/WordPress#125]
WordPress core updates should be [applied from this upstream](https://pantheon.io/docs/upstream-updates/). Therefore we should disable the WordPress dashboard notification to update WordPress core from WordPress itself as doing so can cause merge conflicts.

Additionally we can add our own update notification and link to the documentation to update in the Pantheon dashboard from the WordPress dashboard.

**Comment by westonruter** [comment]
> Additionally we can add our own update notification and link to the documentation to update in the Pantheon dashboard from the WordPress dashboard.

I think this should be done instead. Instead of _disabling_ the nag, if the nag were _replaced_ with a link to the Pantheon dashboard via the mu-plugin. The update screen likewise could link over to the dashboard instead of prompting to update inside WP, avoiding futile prompts for SSH credentials. Since auto-updates are not enabled on the platform, I think the nags are very much important and even moreso since minor releases cannot be automatically applied yet.

**Comment by ataylorme** [comment]
@westonruter agreed. The current nag message is not filterable so I had to remove it and replace with our own.

See #126

**Comment by jhabdas** [comment]
If I understand the nature of this issue it seems like an IoC which puts Pantheon at risk of a single point of failure should a critical patch release be issued. And what of custom upstreams?

With the WP mirror updating every 15 minutes it seems a Web hook could be used to automatically create pulls in versioned branches against this repo and the entire process automated yeah?

**Comment by CdrMarks** [comment]
Resolved in https://github.com/pantheon-systems/WordPress/commit/771b52e40e729f98338f09e55d8595a4b6df5e97.
