### ISSUE TITLE
Move site specific config out of core files

### ISSUE THREAD

**Issue by tinefin** [pantheon-systems/WordPress#128]
It would be great to completely separate site specific config from upstream / core files.
wp-config.php is currently a mix of both. 

Context:
When Pantheon customers apply upstream updates, they can get merge conflicts on wp-config.php. This file is both a part of core, plus it is the file referenced in Pantheon docs to add site specific redirects etc in.
If "Auto resolve conflicts" is checked, recent site specific config can "disappear" as this (rightfully) favors upstream file content.
The alternative is to resolve merge conflicts locally in git.

It would be great to separate core and site code completely to avoid this. A wp-config-site.php (name up for discussion) file could be added at the end of the file to contain site specific configuration.

We could also add a wp-config-site.sample.php file with common custom config in comments if we want to (redirect to https and standardize on www comes to mind) .
https://pantheon.io/docs/redirects/#require-https-and-standardize-domain

The recently added local dev config should also be moved:
https://github.com/pantheon-systems/WordPress/blob/master/wp-config.php#L93-L115

**Comment by carl-alberto** [comment]
Also getting these troubles lately in support that people looses their wp-config customization when updating WP core an using the auto-resolve conflict, is there a way to exclude it in the auto updates @greg-1-anderson @ataylorme ? 

It maybe a good addition in this doc https://pantheon.io/docs/core-updates/#apply-upstream-updates-via-the-site-dashboard that they must put back their wp-config customizations after a auto-resolve core update

If not, I would be glad to help by trying out @tinefin 's proposed solution with a PR

**Comment by greg-1-anderson** [comment]
We can't exclude wp-config.php from updates. Conflicts in wp-config.php only cause problems when there is an upstream change to this file, and if it changes, then the downstream sites are not going to want to miss out on those updates.

I think that the suggestion from @tinefin is the best. I think that we should both have a wp-pantheon-config.php file for all of the Pantheon-specific configurations, and we should also include an empty wp-nameingthingsishard-config.php file that we instruct folks to put their changes into.

It will take folks a little work to update to this new scheme, but once this work is done, then conflicts in wp-config.php will be a thing of the past.

The ideal time to do this change would be at the same time that the WordPress upstream introduces a change to wp-config.php. Otherwise we'll introduce an extra merge conflict that folks wouldn't otherwise encounter. There's no difference for folks that pay attention and do the (minimal) work, but some customers are going to ignore us and keep getting conflicts. It would be appropriately sensitive to make at least minimal accommodations for this group.

**Comment by dylanjameswagner** [comment]
I would suggest/prefer any naming of such files be `wp-config-pantheon.php` and `wp-config-nameingthingsishard.php` because those files will live adjacent to the base `wp-config.php` and be more easily identifiable as related.

**Comment by carl-alberto** [comment]
To add on this, auto merge conflicts in core WP updates also breaks sites that uses custom `$table_prefix` other than `wp_`.

**Comment by CdrMarks** [comment]
Resolved in https://github.com/pantheon-systems/WordPress/commit/1ddd8b6a89e884cb86f8a5dd876301418b65cae7.
