### ISSUE TITLE
web_docroot: true upgrade breaks site

### ISSUE THREAD

**Issue by hirowatari** [pantheon-systems/WordPress#157]
### Steps to reproduce

1. set `web_docroot: true` in pantheon.yml
2. upgrade site in Pantheon applying that adds pantheon link to login form

### Behaviour
* wp-content folder is created in the root with new pantheon-login-form-mods.php
 etc.
* web/wp-content/mu-plugins/pantheon.php is edited to reference 'pantheon/pantheon-login-form-mods.php' that was created in the wrong place
* Fatal error shown when trying to access site

### Expected Behaviour
web/wp-content folder is used

**Comment by greg-1-anderson** [comment]
This behavior is currently unsupported.

1. In order to use `web_docroot: true`, you must use an upstream that also has a relocated document root
2. Pantheon does not maintain any upstreams with a relocated docroot at the moment. If this becomes a common feature request, we may begin doing this.

To use a relocated document root with Pantheon, please use https://github.com/pantheon-systems/example-wordpress-composer

**Comment by hirowatari** [comment]
Cool.  Perhaps documenting that might be wise, or maybe I just missed it.  Either way, thanks for the quick response.
