### ISSUE TITLE
Provide sample/example for a wp-config-local.php

### ISSUE THREAD

**Issue by dylanjameswagner** [pantheon-systems/WordPress#178]
I routinely create a `wp-config-local-sample.php` for every Pantheon project so that future team members don't have to figure out what should be in this file. The `-sample` naming follows the convention set by the `wp-config-sample.php` from WordPress core where the developer would create THIER `wp-config-local.php` by duplicating and renaming this file and editing it as needed.

The lack of reference for this file is exemplified in issue #59 where a user attempted to create a `wp-config-local.php` from the WordPress core `wp-config-sample.php`.

I usually don't provide any inline documentation in this file, but I can understand the argument for having the same inline documentation that is found in the standard `wp-config.php`.

	<?php
	define('DB_NAME',     'database_name_here');
	define('DB_USER',     'username_here');
	define('DB_PASSWORD', 'password_here');
	define('DB_HOST',     'localhost');
	define('DB_CHARSET',  'utf8');
	define('DB_COLLATE',  '');

	define('AUTH_KEY',         'put your unique phrase here');
	define('SECURE_AUTH_KEY',  'put your unique phrase here');
	define('LOGGED_IN_KEY',    'put your unique phrase here');
	define('NONCE_KEY',        'put your unique phrase here');
	define('AUTH_SALT',        'put your unique phrase here');
	define('SECURE_AUTH_SALT', 'put your unique phrase here');
	define('LOGGED_IN_SALT',   'put your unique phrase here');
	define('NONCE_SALT',       'put your unique phrase here');

	define('WP_DEBUG',         true);
	define('WP_DEBUG_LOG',     true);
	define('WP_DEBUG_DISPLAY', true);

	define('WP_AUTO_UPDATE_CORE', false);

	define('WP_HOME',    'http://' . $_SERVER['HTTP_HOST']);
	define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);

**Comment by ataylorme** [comment]
We can probably just link to https://pantheon.io/docs/local-development/#drupal-8-and-wordpress

**Comment by ataylorme** [comment]
@dylanjameswagner there is already a sample `wp-config-local.php` file maintained by the Pantheon documentation team. Rather than maintain the example here as well I opened #207 to add some more instructions, with a link to that example, in the README.

**Comment by dylanjameswagner** [comment]
@ataylorme The suggestion is to provide it within the repo, with all of the elements expected by the `wp-config.php` without having to seek out the documentation.

**Comment by ataylorme** [comment]
> The suggestion is to provide it within the repo, with all of the elements expected by the wp-config.php without having to seek out the documentation

I understand but am reluctant to maintain file contents here that are already being maintained by our documentation team. If there are future changes we would need to coordinate updates to both places.

@greg-1-anderson is the maintainer of this repository so I think the decision on whether or not to include a new file should fall to him.

**Comment by greg-1-anderson** [comment]
I am not concerned about keeping wp-config.php in sync with the Pantheon documentation. That much is manageable. The issue is that wp-config.php is commonly customized in WordPress sites. If we made any substantial changes to this file, or even minor changes, we would probably cause a lot of git conflicts.

The default behavior is to just leave everything here as-is. There are two ways forwar, though:

1. Experiment with some actual customized wp-config.php files, and see what sort of changes could be made such that conflicts were minimized. Estimate the impact on customers.

2. Make a brand-new WordPress upstream with a clean wp-config.php file. Make all new sites start with this upstream. Write some documentation on how existing sites can switch to the new upstream with Terminus, and how to fix any merge conflicts.

We would need Product to sign off on either of these strategies. While the improvements suggested here would be of benefit, it seems to me that the costs of 1. or 2. would be too high to justify the change (& I don't think "just let people suffer through their merge conflicts without analyzing their costs" would be a viable option).

**Comment by ataylorme** [comment]
@greg-1-anderson I think you misunderstand the request. @dylanjameswagner does not wish to alter the `wp-config.php` file but rather introduce an example local config file, similar to the WordPress convention of `wp-config-sample.php`. The Pantheon `wp-config` file in this repo already [accounts for the presence of a `wp-config-local.php` file](https://github.com/pantheon-systems/WordPress/blob/default/wp-config.php#L11:L20).

Adding `wp-config-local-sample.php` (or similar) would just make it easier for users to copy that to `wp-config-local.php` and replace values rather than having to navigate to the docs and copy/paste the `wp-config-local.php` example there.

**Comment by greg-1-anderson** [comment]
You're right I confused this with another proposal to simplify wp-config.php and factor out the Pantheon customizations. I'm fine with adding an example local config file for folks to rename and customize. PRs welcome. Should match the existing documentation, and both versions should have links to the other.

**Comment by dylanjameswagner** [comment]
I have submitted a pull request for this issue, see #211.
