### ISSUE TITLE
Pre-config WP_TEMP_DIR on Pantheon

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/WordPress#25]
We can prevent the unsafe use of global `/tmp` by supplying a `WP_TEMP_DIR` constant in our `wp-config.php`. It would point to `/srv/bindings/<binding-id>/tmp`.

This should be a one-liner in our area of the config file. Should be safe to roll into the next point release from upstream.

**Comment by joshkoenig** [comment]
@greg-1-anderson @TeslaDethray heads up on this. We should get a PR ready for this and then roll it into the next upstream point release. It would be ideal for us to use this opportunity to get Sara leveled-up on helping to maintain the upstream.

**Comment by danielbachhuber** [comment]
@joshkoenig There's two system-level implementations of this issue: https://github.com/pantheon-systems/WordPress/blob/master/wp-includes/functions.php#L1631-L1639

* `sys_temp_dir`, used by `sys_get_temp_dir()` is an ini setting available in PHP 5.5
* WordPress falls back to a `upload_tmp_dir` ini setting when `sys_get_temp_dir()` isn't available. 

To force the use of a safe temp directory, wouldn't it be preferable to do this at the system-level, instead of making it somewhat optional in wp-config?

If you want to do it within WordPress, #32 sets `WP_TEMP_DIR` in `wp-config.php` based on wp-config's path, as I don't see the `<binding-id>` exposed in an environment variable.

**Comment by joshkoenig** [comment]
Fixed in #32
