### ISSUE TITLE
What is the difference between the 'default' and 'master' branch in this repo?

### ISSUE THREAD

**Issue by jonnymaceachern** [pantheon-systems/WordPress#322]
I see that, as the name indicates, `default` is the default branch for this repo, but I also noticed the `master` branch still exists, and with recent commits.

I'm starting to work with Custom Upstreams and want to be sure I'm forking the proper branch.

**Comment by jspellman814** [comment]
@jonnymaceachern The `default` branch is where PRs are merged, and has [CI](https://github.com/pantheon-systems/WordPress/tree/default/.circleci) that copies `default` to `master` after removing the CI directories. This allows customers to clone `master` and implement their own CI without needing to worry about potential merge conflicts.

As mentioned in the [Custom Upstream documentation](https://pantheon.io/docs/create-custom-upstream#pull-in-core-from-pantheons-upstream), be sure to merge in the `master` branch from Pantheon's upstream.

**Comment by namespacebrian** [comment]
To address an unasked question, Pantheon is working on moving away from the `master` branch name.. it's just taking time because there are so many parts of the system that have assumed it as a primary branch name which have to be reworked to support variable primary branch names and provide migration paths for everything.  We can't just rename everyone's primary branch because that would be enormously disruptive.  Many customers have their own CI systems which will need to be adjusted and we need to let them do that on their own timelines, etc.  It's highly non-trivial.
