### ISSUE TITLE
Examine assumptions about redirecting on cache clearing operations

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/WordPress#67]
Currently, when `flush_site()` or `clean_specific_page()` are invoked, we do a `wp_redirect()`:

https://github.com/pantheon-systems/WordPress/blob/master/wp-content/mu-plugins/pantheon/pantheon-cache.php#L244

As pointed out on Power Users, these are add_action'ed to admin actions, and the redirect may well interfere with other operations by cutting short the execution path. We should probably re-think the circumstances under which these are invoked; it may not be wise to always hijack the page transaction with a redirect.

**Comment by jhabdas** [comment]
Bump

**Comment by nullvariable** [comment]
@joshkoenig I realize this issue is super old, so apologies! :ghost: 

In reviewing the code, I don't think this is an issue, the action for `flush_site` is a post hook, which is only triggered when a post request with a matching hook name is submitted. If you don't redirect here, WordPress doesn't know what to do, and just returns a blank screen. Standard use of this hook in all the examples that I could find does a redirect and an exit like we're doing here.

Relevant docs: https://developer.wordpress.org/reference/hooks/admin_post_action/

I think that we can close this issue.
