### ISSUE TITLE
Cache: Undefined index error when post permalink has no query string

### ISSUE THREAD

**Issue by TimothyBJacobs** [pantheon-systems/WordPress#9]
On line 361, the `query` portion of the URL is used without checking if it exists.

https://github.com/pantheon-systems/WordPress/blob/master/wp-content/mu-plugins/pantheon/pantheon-cache.php#L361

`query` should be checked with `isset()` before being used.

**Comment by danielbachhuber** [comment]
@joshkoenig This was originally valid in the [3.9.2 tag](https://github.com/pantheon-systems/WordPress/blob/3.9.2/wp-content/mu-plugins/pantheon/pantheon-cache.php#L361) but no longer valid as of [4.1.0](https://github.com/pantheon-systems/WordPress/blob/4.1.0/wp-content/mu-plugins/pantheon/pantheon-cache.php#L365-L371) as it was fixed in 9bf22e0d5acd2aea3982ddf8a5851e58c9631459
